### ISSUE TITLE
Inline action tags do not terminate background color at end of tag

### ISSUE THREAD

**Issue by tekhaus** [timdmackey/vscode-mechanic-liquid#3]
Typical inline usage is for simple echoes and cache actions. The inline query action does highlight properly, so presumably this is possible?

![image](https://user-images.githubusercontent.com/1009347/117343222-ece94e00-ae58-11eb-8e23-fc4a7a4d9db1.png)

**Comment by timdmackey** [comment]
I think this should be fairly straightforward to fix. It's a weird one because it only shows up if you have **another** `{% endaction %}` tag somewhere after the inline action. I just need to create an exclusion so both cases highlight correctly.

**Comment by timdmackey** [comment]
This should be resolved in dcb09eb9695b6a229b33b821a6ddbd94313088d8. I've pushed the update to the published version on the marketplace. Let me know if you have any more issues!

**Comment by tekhaus** [comment]
Beautiful, thank you for the update!
